name: Create version number

on:
  workflow_call:
    outputs:
      NUGETVERSIONV2:
        description: "Nuget version"
        value: ${{ jobs.version.outputs.NUGETVERSIONV2 }} 

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      NUGETVERSIONV2: ${{ steps.gitversion.outputs.semVer   }}

    steps:
      - uses: actions/checkout@v7  
        with:
          fetch-depth: 0
  

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.5.0
        with:
          versionSpec: '6.x.x'
 
    
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v4.5.0

     